Rename to NumFetch + Minor Changes
Tim-ats-d/Nfetch pull request #2
Opened 2021-02-10 16:21 UTC by The-ZmaZe

- Rename to NumFetch according to NumX scripts (i.e. NumCraft)

- Added RAM and Screen

- Add numfetch() function to allow uses in shell

2021-02-10 19:29 UTC, Tim-ats-d commented on numfetch.py
> +__author__ = ("Tim-ats-d@github.com", "The-ZmaZe@github.com")
Not necessary, right?

2021-02-10 19:33 UTC, Tim-ats-d requested changes
Thank for this pull request.

2021-02-10 19:33 UTC, Tim-ats-d commented on numfetch.py
> +__author__ = ("Tim-ats-d@github.com", "The-ZmaZe@github.com")
Not necessary, right?

2021-02-10 19:33 UTC, Tim-ats-d commented on numfetch.py
> +def numfetch(ascii:str="omega"):
```suggestion
def numfetch(ascii: str = "omega"):
```
PEP8 fix.

2021-02-11 17:08 UTC, The-ZmaZe commented on numfetch.py
> +__author__ = ("Tim-ats-d@github.com", "The-ZmaZe@github.com")
Sure

2021-02-12 23:43 UTC, merged